version: '3.4'
services:
  frontend:
    build: .
    image: cloudhost/frontend_production:latest
    ports:
      - '8080:80'
    networks: 
      - cloudhost-backend_app


networks:
  cloudhost-backend_app:
    external: true
