version: '3.5'
services:
  frontend:
    build: .
    image: cloudhost/frontend_production:1.0.0
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=cloudhost-frontend'
      - 'traefik.docker.network=traefik'
      - 'traefik.frontend.rule=Host:cloudhost.hsrw.eu'
      - 'traefik.port=80'
    networks:
      - traefik


networks:
  traefik:
    external: true
