version: '3.5'
services:
  frontend:
    build:
      context: .
      target: modules
    image: cloudhost/frontend_development:latest
    env_file:
      - .env.development
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=cloudhost-frontend'
      - 'traefik.docker.network=traefik'
      - 'traefik.frontend.rule=Host:cloudhost.hsrw.eu'
      - 'traefik.port=8080'
    command: npm run serve
    volumes:
      - .:/usr/app/frontend/
      - /usr/app/frontend/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - cloudhost-backend_app
      - traefik

networks:
  cloudhost-backend_app:
    external: true
  traefik:
    external: true
