version: '3.5'
services:
  frontend:
    build:
      context: .
      target: modules
    image: cloudhost/frontend_development:1.0.0
    env_file:
      - .env.development
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=cloudhost-frontend'
      - 'traefik.docker.network=traefik'
      - 'traefik.frontend.rule=Host:cloudhost.localhost'
      - 'traefik.port=8080'
    command: npm run serve
    volumes:
      - .:/usr/app/frontend/
      - /usr/app/frontend/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - traefik

networks:
  traefik:
    external: true
