version: '3.5'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.staging
    image: cloudhost/frontend_staging:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=cloudhost-frontend'
      - 'traefik.docker.network=traefik'
      - 'traefik.frontend.rule=Host:staging.cloudhost.hsrw.eu'
      - 'traefik.port=80'
    networks:
      - cloudhost-backend_app
      - traefik


networks:
  traefik:
    external: true
